### ISSUE TITLE
Replace "sleep 5" with check for service

### ISSUE THREAD

**Issue by seroyer** [opiproject/opi-poc#94]
In many files there are instances of
`echo wait 5s... && sleep 5s`

For example in:
integration/docker-compose.xpu.yml
integration/docker-compose.spdk.yml
integration/scripts/integration.sh

That is a fragile approach at best.  Instead you can either make checks for the various services or replace the curl calls with functions that check for sets of HTTP return values and retries.

**Comment by glimchb** [comment]
since I put `healthcheck` everywhere, we can depend on healthy state of the container instead of curls...

**Comment by glimchb** [comment]
partially trying it here as an example https://github.com/opiproject/opi-poc/pull/90/commits/987f35eb4349d9ac8959d1f8ef583c679a5082b1
```
            for i in `seq 1 10`; do sleep 1; ./rpc.py spdk_get_version || continue; done  && \
```

**Comment by glimchb** [comment]
fixed by https://github.com/opiproject/opi-poc/commit/5c6c6d46309fe6b34285f1c11c30843421b4a187

**Comment by seroyer** [comment]
It is better, but not completely fixed.  Currently still depending on sleep 5s for redfish and tftp for example.

**Comment by seroyer** [comment]
Ideally we'd wait until all of the services are running and healthy before running tests.  

for example:
```
$ docker-compose ps --format json | jq '.[] | "\(.Service) \(.State) \(.Health)"'
"host-bmc running healthy"
"host-bmc-redfish running healthy"
"host-bmc-ssh running healthy"
"host-cpu running healthy"
"host-cpu-ssh running healthy"
"otel-gw-collector running unhealthy"
"pxe running healthy"
"spdk-target running unhealthy"
"sztp running unhealthy"
"xpu-bmc running healthy"
"xpu-bmc-redfish running healthy"
"xpu-bmc-ssh running healthy"
"xpu-cpu running healthy"
"xpu-cpu-ssh running healthy"
"xpu-spdk running healthy"
"xpu-telegraf running "
"prometheus running "
```

1) Could wrap that in a loop with some greps.  
2) Could write a client (eg python program) that checks the state.  
3) Or we could just wrap every curl (etc) call in a loop, which is the approach we seem to be starting down.

I tend to think that option 2 will be the best long term.
